---
name: RHEL kernel test on ESXi 7.0

on:
  pull_request:
    branches:
      - "*"

jobs:
  firmware_test:
    strategy:
      matrix:
        # firmware: [bios, efi]
        firmware: [bios]
    name: Run kernel test on ESXi 7.0 VM ${{ matrix.firmware }}
    runs-on: kite-runner

    steps:
      - name: Checkout kite-testbed repository
        uses: actions/checkout@v2

      - name: Checkout kite-deploy repository
        uses: actions/checkout@v2
        with:
          repository: virt-s1/kite-deploy
          path: kite-deploy

      - name: Checkout kite-test repository
        uses: actions/checkout@v2
        with:
          repository: virt-s1/kite-test
          path: kite-test

      - name: Deploy ESXi ${{ matrix.firmware }} VM
        run: cd kite-deploy && ansible-playbook -v -i inventory -e esxi_firmware=${{ matrix.firmware }} -e cloud_platform=esxi deploy.yaml

      - name: Upgrade kernel
        run: |
          GUEST_IP=$(awk -F "=" '/guest_ip/ {print $2}' kite-deploy/inventory)
          ansible-playbook -v -i inventory -e guest_ip=$GUEST_IP upgrade-kernel.yaml

      - name: Run test
        run: |
          cd kite-test && \
          GUEST_IP=$(awk -F "=" '/guest_ip/ {print $2}' kite-deploy/inventory) && \
          test/check-ltp -vst --user=admin --address=$GUEST_IP

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: ltp-console-output-${{ matrix.firmware }}
          path: ./log

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: test-log-${{ matrix.firmware }}
          path: ./Test*FAIL.log.gz

      - name: Remove ESXi VM
        if: ${{ always() }}
        run: cd kite-deploy && ansible-playbook -v -i inventory -e cloud_platform=esxi remove.yaml

      - name: Remove runner
        if: ${{ always() }}
        run: |
          RUNNER_NAME=$(cat /etc/hostname)
          curl -X PUT $KITE_CONTROLLER_API_NETLOC/runner/delete/$RUNNER_NAME > /dev/null 2>&1 &
